MarketWeb/Areas/Admin/Controllers/CompanyController.cs
using Market.DataAccess.Data;
using Market.DataAccess.Repository;
using Market.DataAccess.Repository.IRepository;
using Market.Models;
using Market.Models.ViewModel;
using Market.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace MarketWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetails.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;// used to access wwwroot folder
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Company> Companies = _unitOfWork.CompanyRepository.GetAll().ToList();
            return View(Companies);
        }

        public IActionResult CreateOrUpdate(int? id)
        {

            if (id == null || id == 0)
            {
                // create
                return View(new Company());
            }
            else
            {
                // update
               Company company = _unitOfWork.CompanyRepository.Get(u => u.Id == id);
                return View(company);
            }
        }

        [HttpPost]
        public IActionResult CreateOrUpdate(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    _unitOfWork.CompanyRepository.Add(company);
                    TempData["success"] = "Company created successfully";
                }
                else
                {
                    _unitOfWork.CompanyRepository.Update(company);
                    TempData["success"] = "Company updated successfully";
                }

                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> Companies = _unitOfWork.CompanyRepository.GetAll().ToList();
            return Json(new { data = Companies });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var companyToBeDeleted = _unitOfWork.CompanyRepository.Get(u => u.Id == id);
            if (companyToBeDeleted == null)
            {
                return Json(new {success = false, message = "Error while deleting"});
            }

            _unitOfWork.CompanyRepository.Remove(companyToBeDeleted);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion

    }
}

MarketWeb/Areas/Admin/Views/Company/CreateOrUpdate.cshtml
@model Company

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id!=0?"Update":"Create") Company</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden/>
            <div class="row">
                <div class="col-12">
                    <div class="p-3">
                        @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@

                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow"/>
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow"/>
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="StreetAddress" class="form-control border-0 shadow"/>
                            <label asp-for="StreetAddress" class="ms-2"></label>
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" class="form-control border-0 shadow"/>
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" class="form-control border-0 shadow"/>
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" class="form-control border-0 shadow"/>
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                        <div class="pt-3 d-flex gap-2">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-check-circle"></i> @(Model.Id != 0 ? "Update" : "Create") Company
                            </button>
                            <a asp-controller="Company" asp-action="Index" class="btn btn-outline-secondary">
                                <i class="bi bi-arrow-left-circle"></i> Back to List
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        tinymce.init({
          selector: 'textarea',
          plugins: [
            'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'lists', 'table', 'visualblocks', 'wordcount',
            'checklist', 'mediaembed', 'casechange', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'advtemplate', 'ai', 'uploadcare', 'mentions', 'tinycomments', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown','importword', 'exportword', 'exportpdf'
          ],
          toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | addcomment showcomments | spellcheckdialog a11ycheck typography uploadcare | align lineheight | checklist numlist bullist indent outdent | emoticons charmap',
          tinycomments_mode: 'embedded',
          tinycomments_author: 'Author name',
          mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
          ],
          ai_request: (request, respondWith) => respondWith.string(() => Promise.reject('See docs to implement AI Assistant')),
          uploadcare_public_key: 'f6cc3d5c3157964a814d',
        });
    </script>
    <partial name="_ValidationScriptsPartial" />
}

MarketWeb/Areas/Admin/Views/Company/Index.cshtml
<partial name="_Notification"/>

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Company List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pt-4 pb-3">
            <div class="col-6"></div>
            <div class="col-6 text-end pb-2">
                <a asp-controller="Company" asp-action="CreateOrUpdate" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>  Ceate New Company
                </a>
            </div>
        </div>
        <table id="tblData" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Phone Number</th>
                </tr>
            </thead>
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/company.js"></script>
}